(function(){/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
'use strict';var k,aa="function"==typeof Object.create?Object.create:function(a){var b=function(){};b.prototype=a;return new b},ba=function(a){a=["object"==typeof globalThis&&globalThis,a,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global];for(var b=0;b<a.length;++b){var c=a[b];if(c&&c.Math==Math)return c}throw Error("Cannot find global object");},l=ba(this),m;
if("function"==typeof Object.setPrototypeOf)m=Object.setPrototypeOf;else{var n;a:{var ca={a:!0},p={};try{p.__proto__=ca;n=p.a;break a}catch(a){}n=!1}m=n?function(a,b){a.__proto__=b;if(a.__proto__!==b)throw new TypeError(a+" is not extensible");return a}:null}
var v=m,y=function(a,b){a.prototype=aa(b.prototype);a.prototype.constructor=a;if(v)v(a,b);else for(var c in b)if("prototype"!=c)if(Object.defineProperties){var d=Object.getOwnPropertyDescriptor(b,c);d&&Object.defineProperty(a,c,d)}else a[c]=b[c];a.Ma=b.prototype},z=this||self,B=function(a,b){function c(){}c.prototype=b.prototype;a.Ma=b.prototype;a.prototype=new c;a.prototype.constructor=a;a.Na=function(d,e,h){for(var g=Array(arguments.length-2),f=2;f<arguments.length;f++)g[f-2]=arguments[f];return b.prototype[e].apply(d,
g)}};var C=function(a,b){return a.x*b.x+a.y*b.y},F=function(a,b){return D(b,C(a,b))},D=function(a,b){return G(a.x*b,a.y*b)},G=function(a,b){return{x:a,y:void 0!==b?b:a}};var H=function(a,b,c){a=parseInt(a.getAttribute(b),10);isNaN(a)&&(a=c);return a},I=function(a,b,c){a=parseFloat(a.getAttribute(b));isFinite(a)||(a=c);return a};var J=function(a,b){return window.setTimeout(a,b)};var K=function(a,b,c){c=void 0===c?null:c;var d=document.createEvent("CustomEvent");d.initCustomEvent(a,!0,!0,c);b.dispatchEvent(d);return d},da=function(a,b){b=void 0===b?null:b;var c=void 0===c?null:c;J(function(){var d=K("autoplayended",a,b);c&&c(d)},0)},ea=function(a,b){var c=function(d){a.removeEventListener("attached",c);b(d)};a.addEventListener("attached",c)},fa=function(a){var b=!1,c=null;return function(){b=!0;c||(b&&(a(),b=!1),c=J(function(){c=null;b&&(a(),b=!1)},250))}};var M=["-ms-","-moz-","-webkit-",""],N=function(a,b,c){var d=void 0===d?!1:d;for(var e,h,g=0;g<M.length;g++)e=M[g]+b,h=(d?M[g]:"")+c,a.style.setProperty(e,h)};var O=function(a){return"gwd-page"==a.tagName.toLowerCase()||"gwd-page"==a.getAttribute("is")},ha=function(a){if(O(a))return a;for(;a&&9!=a.nodeType;)if((a=a.parentElement)&&O(a))return a;return null},ia=function(a,b,c,d){d=(void 0===d?"":d)||b;a.hasAttribute(b)?(a=a.getAttribute(b),c.setAttribute(d,a)):c.removeAttribute(d)},ja=function(a){return(a=a.hasAttribute("exit-urls")?a.getAttribute("exit-urls"):"")?a.split(",").map(function(b){return b.trim()}):[]};function P(a){if(Error.captureStackTrace)Error.captureStackTrace(this,P);else{var b=Error().stack;b&&(this.stack=b)}a&&(this.message=String(a))}B(P,Error);P.prototype.name="CustomError";var R=function(a,b){a=a.split("%s");for(var c="",d=a.length-1,e=0;e<d;e++)c+=a[e]+(e<b.length?b[e]:"%s");P.call(this,c+a[d])};B(R,P);R.prototype.name="AssertionError";var ka=function(a,b,c){if(!a){var d="Assertion failed";if(b){d+=": "+b;var e=Array.prototype.slice.call(arguments,2)}throw new R(""+d,e||[]);}return a},la=function(a,b){throw new R("Failure"+(a?": "+a:""),Array.prototype.slice.call(arguments,1));};var S=function(a,b){this.X=b===ma?a:""};S.prototype.xa=!0;S.prototype.wa=function(){return this.X.toString()};S.prototype.toString=function(){return this.X.toString()};var na=/^(?:(?:https?|mailto|ftp):|[^:/?#]*(?:[/?#]|$))/i,ma={};var oa=function(a){var b=[];if(a){a=a.split(",");for(var c=0;c<a.length;c++)if(!/^[\s\xa0]*$/.test(a[c])){var d=b,e=d.push;var h=a[c];h=h.trim();h=window.Enabler?window.Enabler.getUrl(h):h;var g=document.createElement("gwd-image");g.setAttribute("source",h);e.call(d,g)}}return b},pa=function(a,b){for(var c=0;c<a.length;c++){var d=a[c];"gwd-image"==d.tagName.toLowerCase()&&(null!=b?d.setAttribute("scaling",b):d.removeAttribute("scaling"))}},qa=function(a,b){return"left"==a||"backwards"==a?-b:b},ra=
function(a,b){return(a%b+b)%b};var sa=function(a){var b=a.currentIndex-1;return b-b%a.frameSnapInterval},T=function(a){this.u=a;this.F=null;this.La=!0;this.U=!1};
T.prototype.play=function(a,b,c){var d=this;b=void 0===b?"forwards":b;if(this.u.frameCount&&null==this.F){if(c){var e=Math.floor(a/c);a=c}else e=this.u.frameCount,a/=e;var h=[],g=sa(this.u);c=g;for(var f=0;f<e;f++){if(0<f||!this.La)c=ra(c+qa(b,1),this.u.frameCount);h.push(c)}b=function(){if(h.length){var r=h.shift();d.U=!0;d.u.goToFrame(r+1);d.U=!1;K("frameautoplayed",d.u,{id:r+1})}else d.stop(!0),d.u.goToFrame(g+1)};this.F=window.setInterval(b,a);setTimeout(b)}};
T.prototype.stop=function(a){a=void 0===a?!1:a;!this.U&&this.F&&(window.clearInterval(this.F),da(this.u,{completed:a}),this.F=null)};var ta=["pause-front-media","resume-next-media"],U=function(){var a=HTMLElement.call(this)||this;a.frames=[];a.g=null;a.i=0;a.s=1;a.H=new T(a);a.ma=!1;a.oa=!1;return a};y(U,HTMLElement);k=U.prototype;k.attributeChangedCallback=function(a,b,c){switch(a){case "pause-front-media":this.ma="true"==c;break;case "resume-next-media":this.oa="true"==c}};k.gwdIsLoaded=function(){return!0};k.gwdLoad=function(){};
k.goToFrame=function(a,b){this.stopRotation();0!=this.i&&(a>this.i?a=this.i:1>a&&(a=1),this.ea(a,b))};k.ea=function(a){this.g=a-1};var ua=function(a,b,c,d){if(null!=a.g){var e=a.s;e=ra(a.g+qa(b,void 0===e?1:e),a.s*Math.ceil(a.i/a.s));!d&&("forwards"==b&&e<a.g||"backwards"==b&&e>a.g)||a.goToFrame(e+1,c)}};k=U.prototype;k.goBackwards=function(a,b){ua(this,"backwards",void 0===a?"slide":a,void 0===b?!0:b)};k.goForwards=function(a,b){ua(this,"forwards",void 0===a?"slide":a,void 0===b?!0:b)};
k.rotateOnce=function(a,b){this.H.play(void 0===a?0:a,b)};k.stopRotation=function(){this.H.stop()};k.getFrame=function(a){if(0!=this.i)return this.frames[a-1]};k.va=function(a){var b=a.length;a=a.splice(0,b);for(var c=0;c<b;c++){var d=a[c];"frameshown"==d?K(d,this,{id:this.currentIndex}):K(d,this)}};
l.Object.defineProperties(U.prototype,{currentIndex:{configurable:!0,enumerable:!0,get:function(){return 0<this.i?this.g+1:void 0}},frameSnapInterval:{configurable:!0,enumerable:!0,get:function(){return this.s}},frameCount:{configurable:!0,enumerable:!0,get:function(){return this.i}}});l.Object.defineProperties(U,{observedAttributes:{configurable:!0,enumerable:!0,get:function(){return ta}}});var va="images scaling frame-width frame-height frame-snap-interval num-frames-to-display offset start-frame swipe-axis pause-front-media resume-next-media autoplay-duration autoplay-step-interval disable-gesture exit-urls has-navigation navigation-highlight navigation-thumbnails swipe-threshold-ratio swipe-committed-threshold-ratio transition-duration".split(" "),V=function(){var a=U.call(this)||this;a.V=!1;a.h=null;a.W=null;a.R=!1;a.B=G(0);a.C=null;a.o=!1;a.l=null;a.ia=a.Da.bind(a);a.ka=a.Fa.bind(a);
a.ga=a.Ba.bind(a);a.ha=a.Ca.bind(a);a.ja=a.Ea.bind(a);a.ba=a.ya.bind(a);a.ua=a.Ja.bind(a);a.ta=a.Ia.bind(a);a.sa=a.Ha.bind(a);a.da=a.za.bind(a);a.la=a.Aa.bind(a);a.na=fa(a.Ga.bind(a));a.P=K.bind(null,"firstinteraction",a);a.Y=!1;a.K=[];a.G=a.va.bind(a,a.K);a.Z=0;a.$=0;a.N=0;a.ra=0;a.qa=0;a.T=1;a.O=[];a.S=0;a.pa=1;a.Ka=.7;a.L=0;a.M=!1;a.D=G(0);a.A=G(0);a.m=null;a.fa=-1;a.v=-1;a.ca=[];a.I=G(-1,-1);a.j=G(1,0);a.J=!1;return a};y(V,U);
V.prototype.connectedCallback=function(){if(!this.J){if(this.R=this.hasAttribute("images"))for(;this.firstChild;)this.removeChild(this.firstChild);var a=document.createElement("gwd-gesture");a.className="gesture";this.C=a;this.J=!0}a=this.C;a.addEventListener("pointerover",this.ka,!1);a.addEventListener("pointerout",this.ia,!1);a.addEventListener("pointermove",this.ga,!1);a.addEventListener("track",this.ua,!1);a.addEventListener("trackend",this.ta,!1);a.addEventListener("tap",this.sa,!1);this.addEventListener("frametap",
this.da,!1);this.addEventListener("swipefinished",this.aa,!1);this.addEventListener("transitionend",this.G,!1);this.addEventListener("webkitTransitionEnd",this.G,!1);this.gwdIsLoaded()||((a=ha(this))?a.gwdIsLoaded()&&this.gwdLoad():this.gwdLoad());window.addEventListener("resize",this.na,!1)};
V.prototype.disconnectedCallback=function(){window.removeEventListener("resize",this.na,!1);var a=this.C;a.removeEventListener("pointerover",this.ka,!1);a.removeEventListener("pointerout",this.ia,!1);a.removeEventListener("pointermove",this.ga,!1);a.removeEventListener("track",this.ua,!1);a.removeEventListener("trackend",this.ta,!1);a.removeEventListener("tap",this.sa,!1);this.removeEventListener("frametap",this.da,!1);this.removeEventListener("swipefinished",this.aa,!1);this.removeEventListener("transitionend",
this.G);this.removeEventListener("webkitTransitionEnd",this.G)};
V.prototype.attributeChangedCallback=function(a,b,c,d){if(this.J)switch(a){case "images":this.frames=oa(this.getAttribute("images"));wa(this);W(this);break;case "scaling":pa(this.frames,this.getAttribute("scaling"));break;case "has-navigation":case "navigation-highlight":case "navigation-thumbnails":xa(this);W(this);break;case "transition-duration":case "exit-urls":case "autoplay-duration":case "autoplay-step-interval":X(this);break;case "frame-width":case "frame-height":case "frame-snap-interval":case "num-frames-to-display":case "swipe-axis":X(this);
W(this);break;case "disable-gesture":case "offset":case "start-frame":case "swipe-threshold-ratio":case "swipe-committed-threshold-ratio":W(this);break;default:U.prototype.attributeChangedCallback.call(this,a,b,c,d)}else U.prototype.attributeChangedCallback.call(this,a,b,c,d)};
var X=function(a){var b=H(a,"num-frames-to-display",1),c=H(a,"frame-snap-interval",1),d=H(a,"transition-duration",600),e=H(a,"frame-width",-1),h=H(a,"frame-height",-1),g=I(a,"autoplay-duration",3E3),f=I(a,"autoplay-step-interval",0);a.I.x=e;a.I.y=h;e="y"===a.getAttribute("swipe-axis");a.j=G(e?0:1,e?1:0);-1!=C(a.I,a.j)?b=-1:0<b&&c>b&&(c=b);a.ca=ja(a);a.v=b;a.s=c;a.N=d;a.Z=g;a.$=f},W=function(a){var b=G(a.clientWidth,a.clientHeight);a.m&&(b.y-=36,a.W.style.height=b.y+"px");var c=I(a,"swipe-threshold-ratio",
.1),d=I(a,"swipe-committed-threshold-ratio",.5),e=a.j,h=a.v,g=a.I,f=a.frames,r=parseInt(a.getAttribute("offset"),10);isNaN(r)&&(r=0);r=D(e,r);g=G(-1==g.x?b.x:g.x,-1==g.y?b.y:g.y);if(a.hasAttribute("offset")){a:{var t=g.x,q=g.y,A=!0;if(a.hasAttribute("clamp-frame-size-to-image")){var w=a.getAttribute("clamp-frame-size-to-image");"true"==w?A=!0:"false"==w&&(A=!1)}if(A)if(w=a.hasAttribute("scaling")?a.getAttribute("scaling"):"contain",A="contain"==w,!A&&"none"!=w||0==t||0==q)f={width:t,height:q};else{for(var L=
w=-1,Ba=f.length,Q=0;Q<Ba;Q++){var u=f[Q];if("img"!=u.tagName.toLowerCase()&&"gwd-image"!=u.tagName.toLowerCase()){f={width:t,height:q};break a}var x=u.assetWidth?u.assetWidth:u.naturalWidth,E=u.assetHeight?u.assetHeight:u.naturalHeight;0<x&&0<E&&(A?x/E<t/q?(u=x/E*q,x=q):(u=t,x=E/x*t):(u=x,x=E),w=Math.max(w,u),L=Math.max(L,x))}f={width:-1!=w?Math.min(t,w):t,height:-1!=L?Math.min(q,L):q}}else f={width:t,height:q}}1==e.x?g.x=f.width:g.y=f.height}1<h&&(f=D(e,h-1),f=G(f.x*r.x,f.y*r.y),f=F(G((b.x-f.x)/
h,(b.y-f.y)/h),e),f.x&&(g.x=f.x),f.y&&(g.y=f.y));f=2<h?1+Math.ceil(h/2-1):1;t=parseInt(a.getAttribute("start-frame"),10);isNaN(t)&&(t=f);f=F(G(g.x+r.x,g.y+r.y),e);q=1+2*Math.floor((C(e,b)-C(e,g))/(2*C(e,f)));if(1>q||!isFinite(q))q=1;b=G((b.x-g.x)/2,(b.y-g.y)/2);0<h&&0==h%2&&(e=F(G(g.x+r.x,g.y+r.y),e),b.x-=.5*e.x,b.y-=.5*e.y,q+=1);e=a.hasAttribute("disable-gesture");a.A=g;a.D=b;a.T=q;a.L=C(f,a.j);a.pa=t;a.o=e;a.ra=C(a.A,a.j)*c;a.qa=C(a.A,a.j)*d;c=F(a.D,G(a.j.y,a.j.x));for(e=0;e<a.i;e++)d=a.frames[e].style,
d.left=c.x+"px",d.top=c.y+"px",d.width=a.A.x+"px",d.height=a.A.y+"px",c.x+=f.x,c.y+=f.y;a.B=G(0);a.h&&(Y(a,0,0,0),c=F(a.D,a.j),a.h.style.left=c.x+"px",a.h.style.top=c.y+"px");a.g=null;a.goToFrame(a.pa,"none")};k=V.prototype;k.gwdIsLoaded=function(){return this.V};k.gwdLoad=function(){if(!this.V&&!this.h){if(this.R)var a=oa(this.getAttribute("images"));else{a=this.childNodes;for(var b=[],c=0,d=a.length;c<d;c++){var e=a[c];e.nodeType==Node.ELEMENT_NODE&&b.push(e)}a=b}this.frames=a;wa(this)}};
k.goBackwards=function(a,b){return U.prototype.goBackwards.call(this,a,void 0===b?!1:b)};k.goForwards=function(a,b){return U.prototype.goForwards.call(this,a,void 0===b?!1:b)};
k.ea=function(a,b){var c=this.s;var d=this.i;var e=this.v;--a;a=a-a%c+Math.floor((c-1)/2);0>a?a=0:a>=d&&(a=d-1);1<e&&(c=a-Math.floor((e-1)/2),e=c+e-1,0>c&&e<d-1&&(a+=Math.min(-c,d-e-1)),e>=d&&0<c&&(a-=Math.min(e-d+1,c)));d=a;if(null!=this.g&&this.g!=d){if(this.ma)for(e=Array.prototype.slice.call(this.frames[this.g].querySelectorAll("video, gwd-youtube, audio,gwd-video,gwd-audio")),a=0;a<e.length;a++)c=e[a],c.pause&&c.pause();if(this.oa)for(e=Array.prototype.slice.call(this.frames[d].querySelectorAll("video, gwd-youtube, audio,gwd-video,gwd-audio")),
a=0;a<e.length;a++)c=e[a],c.play&&c.play()}e=this.g;this.g=d;d=D(this.j,-this.L*this.g);Y(this,"none"!=b?this.N:0,d.x,d.y);this.B=d;if(this.S)for(b=Math.floor((this.T-1)/2),d=0;d<this.T;d++)if(a=this.g-b+d,!(0>a||a>=this.i||this.O[a]||(this.O[a]=!0,--this.S))){this.K.push("allframesviewed");break}e!=this.g&&(ya(this,this.g+1),this.K.push("frameshown"),this.K.push("swipefinished"));this.Y||this.G()};
var Y=function(a,b,c,d){a.Y=0<b;N(a.h,"transition","transform "+b+"ms");N(a.h,"transform","translate3d("+c+"px,"+d+"px,0)")},wa=function(a){if(a.J){for(;a.firstChild;)a.removeChild(a.firstChild);a.m=null;a.h&&(a.h.removeEventListener("pageload",a.la,!1),a.h.removeEventListener("mouseover",a.ja,!0),a.h.removeEventListener("mouseout",a.ha,!0),a.h.removeEventListener("click",a.ba,!0));for(var b=a.frames,c=document.createElement("gwd-page"),d=0;d<b.length;d++){var e=b[d];N(e,"user-select","none");e.classList.add("frame");
c.appendChild(e)}ea(c,c.gwdLoad.bind(c));a.h=c;a.h.className="container";a.h.addEventListener("pageload",a.la,!1);a.h.addEventListener("mouseover",a.ja,!0);a.h.addEventListener("mouseout",a.ha,!0);a.h.addEventListener("click",a.ba,!0);pa(a.frames,a.getAttribute("scaling"));a.i=a.frames.length;b=a.ownerDocument.createElement("div");a.W=b;b.className="matte";b.appendChild(a.h);a.appendChild(a.W);a.appendChild(a.C)}};V.prototype.aa=function(){N(this.h,"transition","transform 0ms")};
V.prototype.Aa=function(a){a.target===this.h&&(this.V=!0,this.S=this.i,this.O=[],X(this),xa(this),W(this),K("allframesloaded",this),this.hasAttribute("autoplay")&&this.H.play(this.Z,"forwards",this.$),K("ready",this))};V.prototype.Ga=function(){X(this);W(this)};V.prototype.rotateOnce=function(a,b){this.H.play(a||this.N,b)};
var Aa=function(a,b){var c=a.i;if(c){var d=a.g;b=za(a,b);a.goToFrame(b+1);d!=b&&(0==b?K("reachleftend",a):b==c-1&&K("reachrightend",a))}},xa=function(a){var b=a.hasAttribute("has-navigation"),c=!!a.m;b&&!c?(b=a.id||a.getAttribute("data-gwd-grp-id"),a.m=a.ownerDocument.createElement("gwd-gallerynavigation"),a.m.setAttribute("for",b),a.classList.add("has-navigation"),a.appendChild(a.m)):!b&&c&&(a.classList.remove("has-navigation"),a.removeChild(a.m),a.m=null);a.m&&(ia(a,"navigation-highlight",a.m,"highlight"),
ia(a,"navigation-thumbnails",a.m,"use-thumbnails"))},za=function(a,b){var c=a.g;Math.abs(b)>a.ra&&(c=0>b?c+a.s:c-a.s);0>c?c=0:c>=a.i&&(c=a.i-1);return c},ya=function(a,b){a.fa!=b&&(a.fa=b,K("frameactivated",a,{id:b||a.currentIndex}))};
V.prototype.Ja=function(a){if(!this.o&&(this.P&&(this.P(),this.P=null),!this.M))if(this.stopRotation(),a=C(G(a.dx,a.dy),this.j),ya(this,za(this,a)+1),Math.abs(a)>this.qa)Aa(this,a),this.M=!0;else{var b=a;if(0<a&&0===this.g||0>a&&this.g===this.i-1)b-=a*this.Ka;Y(this,0,this.B.x+this.j.x*b,this.B.y+this.j.y*b)}};V.prototype.Ia=function(a){this.o||(this.M?this.M=!1:Aa(this,C(G(a.dx,a.dy),this.j)))};
var Z=function(a,b){var c=a.getBoundingClientRect();b=G(b.clientX-c.left,b.clientY-c.top);c=a.j;var d=G(c.y,c.x);c=C(d,b);var e=C(d,a.D);d=C(d,a.A);if(c<e||c>e+d)return null;c=a.j;b=C(c,b)-C(c,a.B)-C(c,a.D);c=Math.floor(b/a.L);return 0>c||c>=a.i||b%a.L>C(a.j,a.A)?null:c};k=V.prototype;
k.Ha=function(a){if(!this.o){this.stopRotation();var b=this.C;var c=this.h;var d=a.clientX,e=a.clientY,h=b.style["pointer-events"];b.style["pointer-events"]="none";d=c.ownerDocument.elementFromPoint(d,e);b.style["pointer-events"]=h;if(b=d)if(c.contains&&1==d.nodeType)b=c==d||c.contains(d);else if("undefined"!=typeof c.compareDocumentPosition)b=c==d||!!(c.compareDocumentPosition(d)&16);else{for(b=d;b&&c!=b;)b=b.parentNode;b=b==c}c=b?d:null;(b=!c)||(b=a.clientX,h=a.clientY,d=!1,"gwd-taparea"===c.tagName.toLowerCase()&&
(d=c.ownerDocument.createEvent("Event"),d.initEvent("action",!0,!0),d.clientX=b,d.clientY=h,d=!c.dispatchEvent(d)),b=!d);b&&(a=Z(this,a),null!=a&&K("frametap",this,{element:this.frames[a],id:a+1}))}};
k.za=function(a){if((a=a.detail&&a.detail.id)&&(a=this.ca[a-1])&&!K("frameexit",this,{url:a}).detail.handled){a instanceof S||a instanceof S||(a="object"==typeof a&&a.xa?a.wa():String(a),ka(na.test(a),"%s does not match the safe URL pattern",a)||(a="about:invalid#zClosurez"),a=new S(a,ma));var b=a;a=z.open;if(b instanceof S&&b.constructor===S)b=b.X;else{var c=typeof b;la("expected object of type SafeUrl, got '"+b+"' of type "+("object"!=c?c:b?Array.isArray(b)?"array":c:"null"));b="type_error:SafeUrl"}a.call(z,
b,"")}};k.Da=function(){this.o||null==this.l||(K("framemouseout",this,{element:this.frames[this.l],id:1+this.l}),this.l=null)};k.Fa=function(a){this.o||(a=Z(this,a),a!=this.l&&(null!=this.l&&K("framemouseout",this,{element:this.frames[this.l],id:1+this.l}),null!=a&&K("framemouseover",this,{element:this.frames[a],id:1+a}),this.l=a))};
k.Ba=function(a){this.o||(a=Z(this,a),a!=this.l&&(null!=this.l&&K("framemouseout",this,{element:this.frames[this.l],id:1+this.l}),null!=a&&K("framemouseover",this,{element:this.frames[a],id:1+a}),this.l=a))};k.Ea=function(a){this.o&&a.target.classList.contains("frame")&&K("framemouseover",this,{element:a.target,id:1+this.frames.indexOf(a.target)})};k.Ca=function(a){this.o&&a.target.classList.contains("frame")&&K("framemouseout",this,{element:a.target,id:1+this.frames.indexOf(a.target)})};
k.ya=function(a){this.o&&a.target.classList.contains("frame")&&K("frametap",this,{element:a.target,id:1+this.frames.indexOf(a.target)})};
l.Object.defineProperties(V.prototype,{firstVisibleFrameIndex:{configurable:!0,enumerable:!0,get:function(){var a=0<this.v&&0<this.i&&null!=this.g?Math.max(1,this.g-Math.floor((this.v-1)/2)+1):void 0;return a}},lastVisibleFrameIndex:{configurable:!0,enumerable:!0,get:function(){var a=0<this.v&&0<this.i&&null!=this.g?Math.min(this.i,this.g-Math.floor((this.v-1)/2)+this.v):void 0;return a}}});l.Object.defineProperties(V,{observedAttributes:{configurable:!0,enumerable:!0,get:function(){return va}}});
customElements.define("gwd-swipegallery",V);}).call(this);
